---
title: timeout
description: Asynchronously rejects after a specified amount of time.
since: 12.3.0
---

### Usage

The `_.timeout` function creates a promise that will reject after a given number of milliseconds. You can provide a custom error message or a function that returns an error to be thrown upon rejection.

```ts
import * as _ from 'radashi'

// Rejects after 1 second with the default "timeout" error message
await _.timeout(1000)

// Rejects after 1 second with a custom error message
await _.timeout(1000, 'Custom timeout message')

// Rejects after 1 second with a custom error object
await _.timeout(1000, () => new Error('Custom error'))
```

### Example with `Promise.race`

One of the most useful ways to use `_.timeout` with `Promise.race` to set a timeout for an asynchronous operation.

```ts
import * as _ from 'radashi'

const someAsyncTask = async () => {
  await _.sleep(10_000)
  return 'Task completed'
}

// Race between the async task and a timeout of 1 second
await Promise.race([someAsyncTask(), _.timeout(1000, 'Task took too long')])
```
